"""Draw the application icon (assets/app.ico, assets/app.png, certpdf/icon.py).

Run from the project folder:  python tools/make_icon.py
"""

import base64
import io
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
SIZE = 1024  # drawn large, then scaled down for smooth edges


def draw() -> Image.Image:
    img = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)

    # Blue rounded tile
    d.rounded_rectangle((40, 40, SIZE - 40, SIZE - 40), radius=200, fill=(23, 74, 132, 255))
    d.rounded_rectangle((40, 40, SIZE - 40, SIZE // 2), radius=200, fill=(31, 95, 168, 255))
    d.rectangle((40, SIZE // 2 - 200, SIZE - 40, SIZE // 2), fill=(31, 95, 168, 255))
    d.rectangle((40, SIZE // 2, SIZE - 40, SIZE // 2 + 1), fill=(23, 74, 132, 255))

    # White sheet of paper with a folded corner
    left, top, right, bottom, fold = 250, 150, 774, 874, 150
    d.polygon([(left, top), (right - fold, top), (right, top + fold), (right, bottom), (left, bottom)],
              fill=(255, 255, 255, 255))
    d.polygon([(right - fold, top), (right - fold, top + fold), (right, top + fold)], fill=(200, 214, 232, 255))

    # ECG trace
    base = 470
    trace = [(left + 40, base), (430, base), (465, base - 60), (500, base), (535, base),
             (565, base + 70), (600, base - 230), (640, base + 150), (672, base), (right - 40, base)]
    d.line(trace, fill=(214, 40, 57, 255), width=38, joint="curve")

    # "PDF" band
    d.rounded_rectangle((left - 60, 610, right - 40, 800), radius=36, fill=(214, 40, 57, 255))
    try:
        font = ImageFont.truetype("DejaVuSans-Bold.ttf", 150)
    except OSError:
        font = ImageFont.load_default()
    text = "PDF"
    box = d.textbbox((0, 0), text, font=font)
    cx, cy = (left - 60 + right - 40) / 2, 705
    d.text((cx - (box[2] - box[0]) / 2 - box[0], cy - (box[3] - box[1]) / 2 - box[1]), text,
           font=font, fill=(255, 255, 255, 255))
    return img


def draw_checkbox(size: int, checked: bool, disabled: bool) -> Image.Image:
    """Checkbox indicator images used instead of the theme's default."""
    scale = 8
    big = size * scale
    img = Image.new("RGBA", (big, big), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    box = (scale, scale, big - scale - 1, big - scale - 1)
    radius = 3 * scale
    if checked:
        fill = (169, 190, 218, 255) if disabled else (31, 95, 168, 255)
        d.rounded_rectangle(box, radius=radius, fill=fill)
        points = [(0.25 * big, 0.52 * big), (0.43 * big, 0.70 * big), (0.76 * big, 0.33 * big)]
        d.line(points, fill=(255, 255, 255, 255), width=int(0.12 * big), joint="curve")
    else:
        outline = (200, 208, 218, 255) if disabled else (130, 146, 166, 255)
        d.rounded_rectangle(box, radius=radius, fill=(243, 246, 250, 255) if disabled else (255, 255, 255, 255),
                            outline=outline, width=int(1.2 * scale))
    return img.resize((size, size), Image.LANCZOS)


def _png_base64(img: Image.Image) -> str:
    buf = io.BytesIO()
    img.save(buf, "PNG", optimize=True)
    return base64.b64encode(buf.getvalue()).decode()


def main() -> None:
    img = draw()
    assets = ROOT / "assets"
    assets.mkdir(exist_ok=True)
    img.resize((256, 256), Image.LANCZOS).save(assets / "app.png")
    img.resize((256, 256), Image.LANCZOS).save(
        assets / "app.ico", sizes=[(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)])

    parts = ['"""Window icons (PNG), generated by tools/make_icon.py."""\n']
    for name, size in (("ICON_PNG_BASE64", 64), ("HEADER_ICON_PNG_BASE64", 44)):
        buf = io.BytesIO()
        img.resize((size, size), Image.LANCZOS).save(buf, "PNG", optimize=True)
        data = base64.b64encode(buf.getvalue()).decode()
        lines = [data[i:i + 76] for i in range(0, len(data), 76)]
        parts.append(f"\n{name} = (\n" + "".join(f'    "{line}"\n' for line in lines) + ")\n")
    checks = []
    for size in (16, 24):
        for state, (checked, disabled) in (("off", (False, False)), ("on", (True, False)),
                                            ("off_disabled", (False, True)), ("on_disabled", (True, True))):
            checks.append(f'    ({size}, "{state}"): "{_png_base64(draw_checkbox(size, checked, disabled))}",\n')
    parts.append("\n# (size, state) -> checkbox indicator PNG\nCHECKBOX_PNG_BASE64 = {\n" + "".join(checks) + "}\n")
    (ROOT / "certpdf" / "icon.py").write_text("".join(parts), encoding="utf-8")


if __name__ == "__main__":
    main()
